import { addDoc, collection, getDocs, serverTimestamp } from 'firebase/firestore';
import { db, APP_ID } from '../services/firebase/config';

// المصدر: قائمة تمارين شاملة (Benches/Bodyweight, Pull-Up & Parallel, Free Weights, Medicine Ball, Core)
// مُصنّفة تلقائياً بحسب العضلة الأساسية المستهدفة (muscleGroup enum) ومُستبعد منها التكرار الداخلي
const IMPORTED_EXERCISES = [
  { name: 'Back Hyperextension', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Body Weight', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Decline Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Lower Abs, Deep Core' },
  { name: 'Bench Dip', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Bench', description: 'Secondary: Lower Chest' },
  { name: 'Seated Leg Tuck', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Hip Flexors' },
  { name: 'Bench Push-Up', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Bench', description: 'Secondary: Front Shoulder, Triceps Long Head' },
  { name: 'Bench Leg Raise (Supine)', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Hip Flexors' },
  { name: 'Elevated Push-Up', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Body Weight', description: 'Secondary: Front Shoulder, Triceps Long Head' },
  { name: 'Dragon Flag', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Upper Abs, Hip Flexors' },
  { name: 'Bench Hip Thrust', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Bench', description: 'Secondary: Hamstrings' },
  { name: 'Bodyweight Step-Up', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Body Weight', description: 'Secondary: Glute Max' },
  { name: 'Decline Bench Leg Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Hip Flexors' },
  { name: 'Bench Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Lower Abs' },
  { name: 'Reverse Hyper (Flat Bench)', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Bench', description: 'Secondary: Hamstrings, Lower Back' },
  { name: 'Donkey Calf Raise', category: 'RESISTANCE', muscleGroup: 'Lower Legs', equipment: 'Body Weight', description: 'Secondary: Lower Calf' },
  { name: 'Weighted Bench Dip', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Bench', description: 'Secondary: Triceps Long Head, Triceps Medial Head' },
  { name: 'Decline Bench Rotational Sit-Up', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Upper Abs' },
  { name: 'Seated Bench Leg Pull-In', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Hip Flexors, Deep Core' },
  { name: 'Decline Reverse Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Upper Abs' },
  { name: 'Leg Raise with Hip Thrust', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Deep Core, Hip Flexors' },
  { name: 'Decline Bench Ab Reach', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Lower Abs, Deep Core' },
  { name: 'Bench Leg Pull-In', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Hip Flexors' },
  { name: 'Side Step-Up', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Body Weight', description: 'Secondary: Glute Max' },
  { name: 'Single-Leg Bench Dip', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Bench', description: 'Secondary: Triceps Lateral Head' },
  { name: 'Decline Oblique Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Upper Abs, Lower Abs' },
  { name: 'Assisted Hyperextension', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Body Weight', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Bench Oblique Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core' },
  { name: 'Decline Bench Leg Raise with Hip Thrust', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Hip Flexors' },
  { name: 'Bench Plank', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Upper Abs, Lower Back, Lower Abs' },
  { name: 'Quadriceps Stretch', category: 'COOL-DOWN', muscleGroup: 'Upper Legs', equipment: 'Body Weight', description: '' },
  { name: 'Decline Bench Knee Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Hip Flexors' },
  { name: 'Forward Step-Up', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Body Weight', description: 'Secondary: Glute Max' },
  { name: 'Bench Rotational Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Upper Abs, Lower Back' },
  { name: 'Bench Jackknife Sit-Up', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Lower Abs, Deep Core' },
  { name: 'Incline Push-Up Depth Jump', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Bench', description: 'Secondary: Front Shoulder, Triceps Long Head' },
  { name: 'Box Jump with Single-Leg Stabilization', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Body Weight', description: 'Secondary: Glute Max' },
  { name: 'Alternating Reverse Hyper (Flat Bench)', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Bench', description: 'Secondary: Hamstrings, Lower Back' },
  { name: 'Three Bench Dip', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Bench', description: 'Secondary: Triceps Lateral Head' },
  { name: 'Single-Leg Reverse Hyper (Flat Bench)', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Bench', description: 'Secondary: Hamstrings, Lower Back' },
  { name: 'Drop Push-Up', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Body Weight', description: 'Secondary: Triceps Long Head' },
  { name: 'Bench Leg and Hip Stretch', category: 'COOL-DOWN', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Glute Max, Deep Core, Lower Back' },
  { name: 'Bench Calf Stretch', category: 'COOL-DOWN', muscleGroup: 'Lower Legs', equipment: 'Bench', description: 'Secondary: Lower Calf' },
  { name: 'Stability Ball Head Tilt', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Exercise Ball', description: 'Secondary: Obliques' },
  { name: 'Decline Bench Alternating Leg Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Hip Flexors, Deep Core' },
  { name: 'Stability Ball Hamstring Contract Relax', category: 'COOL-DOWN', muscleGroup: 'Upper Legs', equipment: 'Exercise Ball', description: 'Secondary: Lower Back' },
  { name: 'Bench Quad Stretch (Supine)', category: 'COOL-DOWN', muscleGroup: 'Upper Legs', equipment: 'Bench', description: '' },
  { name: 'Decline Bench Alternating Knee Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Bench', description: 'Secondary: Deep Core, Hip Flexors' },
  { name: 'Upper Body Chair Stretch', category: 'COOL-DOWN', muscleGroup: 'Shoulders', equipment: 'Body Weight', description: 'Secondary: Lower Chest, Upper Chest' },
  { name: 'Rotational Step-Up', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Body Weight', description: 'Secondary: Glute Max' },
  { name: 'Pull-Up', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Middle Back' },
  { name: 'Dip', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Pullup Bar', description: 'Secondary: Triceps Lateral Head' },
  { name: 'Hanging Leg Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Hip Flexors, Deep Core' },
  { name: 'Parallel Bar Leg Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Hip Flexors' },
  { name: 'Hanging Knee Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Lower Abs' },
  { name: 'Parallel Bar Hip Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Upper Abs' },
  { name: 'Chin-Up (Close Grip)', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Outer Biceps' },
  { name: 'Chin-Up with Knee Raise', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Middle Back' },
  { name: 'Pull-Up (Hammer Grip)', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Outer Biceps' },
  { name: 'Machine Inverted Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Strength Machine', description: 'Secondary: Middle Back, Rear Shoulder' },
  { name: 'One-Arm Hang', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Pullup Bar', description: 'Secondary: Lats' },
  { name: 'Machine Inverted Row (Feet Elevated)', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Strength Machine', description: 'Secondary: Lats' },
  { name: 'Parallel Bar Hip Flexion', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Lower Abs' },
  { name: 'Chin-Up (Mixed Grip)', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Outer Biceps' },
  { name: 'Rear Pull-Up (Wide Grip)', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Middle Back' },
  { name: 'Hanging Knee Raise Rotation', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Lower Abs, Hip Flexors' },
  { name: 'Hanging Pike', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Deep Core, Hip Flexors' },
  { name: 'Windshield Wipers', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Deep Core, Lower Abs' },
  { name: 'Climber Pull-Up', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: '' },
  { name: 'Gironda Sternum Pull-Up', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: '' },
  { name: 'Hanging Knee Raise (Rotational)', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Pullup Bar', description: 'Secondary: Lower Abs, Hip Flexors' },
  { name: 'Rocky Pull-Up', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Outer Biceps' },
  { name: 'Gorilla Chin-Up with Crunch', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Outer Biceps' },
  { name: 'One-Arm Chin-Up', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Pullup Bar', description: 'Secondary: Outer Biceps' },
  { name: 'Dumbbell Lateral Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: '' },
  { name: 'Dumbbell Alternating Bicep Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Dumbbell', description: 'Secondary: Outer Biceps' },
  { name: 'Dumbbell Alternating Hammer Curl', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Dumbbell', description: 'Secondary: Brachialis, Outer Biceps' },
  { name: 'Barbell Deadlift', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Hamstrings, Lower Back' },
  { name: 'Barbell Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Barbell', description: 'Secondary: Outer Biceps' },
  { name: 'Barbell Bent-Over Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Middle Back' },
  { name: 'Barbell Romanian Deadlift', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max, Lower Back' },
  { name: 'Dumbbell Hammer Curl', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Dumbbell', description: 'Secondary: Brachialis, Outer Biceps' },
  { name: 'Dumbbell Triceps Extension', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Dumbbell', description: 'Secondary: Triceps Lateral Head, Triceps Medial Head' },
  { name: 'Dumbbell Shoulder Shrug', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Dumbbell', description: '' },
  { name: 'EZ Bar Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'EZ Curl Bar', description: 'Secondary: Outer Biceps, Brachialis' },
  { name: 'Dumbbell Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Triceps Lateral Head' },
  { name: 'Barbell Military Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Triceps Lateral Head, Side Shoulder' },
  { name: 'Dumbbell Romanian Deadlift', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Lunge', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Kettlebell Goblet Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Kettlebell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Calf Raise', category: 'RESISTANCE', muscleGroup: 'Lower Legs', equipment: 'Dumbbell', description: 'Secondary: Lower Calf' },
  { name: 'Dumbbell Front Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: '' },
  { name: 'Barbell Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Side Shoulder' },
  { name: 'Barbell Standing Calf Raise', category: 'RESISTANCE', muscleGroup: 'Lower Legs', equipment: 'Barbell', description: 'Secondary: Lower Calf' },
  { name: 'Weight Plate Russian Twist', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Weight Plate', description: 'Secondary: Deep Core' },
  { name: 'Dumbbell Bent-Over Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Dumbbell', description: 'Secondary: Middle Back' },
  { name: 'Dumbbell Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Side Bend', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Dumbbell', description: 'Secondary: Deep Core' },
  { name: 'Barbell Shrug', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: '' },
  { name: 'Barbell Upright Row', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Traps' },
  { name: 'Dumbbell Deadlift', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Dumbbell', description: 'Secondary: Hamstrings, Lower Back, Quads' },
  { name: 'Dumbbell Reverse Lunge', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Dumbbell', description: 'Secondary: Quads, Hamstrings' },
  { name: 'Dumbbell Hammer Curl (Cross Body)', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Dumbbell', description: 'Secondary: Brachialis, Outer Biceps, Inner Biceps' },
  { name: 'Dumbbell Walking Lunge', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Middle Back, Rear Shoulder' },
  { name: 'Dumbbell Bent-Over Reverse Fly', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Middle Back, Traps' },
  { name: 'Dumbbell Zottman Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Dumbbell', description: 'Secondary: Top of Forearm, Inner Biceps, Outer Forearm' },
  { name: 'Barbell Glute Bridge', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Hamstrings' },
  { name: 'Weighted Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Barbell', description: 'Secondary: Lower Abs, Deep Core' },
  { name: 'Dumbbell One-Arm Triceps Extension', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Dumbbell', description: 'Secondary: Triceps Lateral Head, Triceps Medial Head' },
  { name: 'Barbell Ab Rollout (Kneeling)', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Barbell', description: 'Secondary: Upper Abs, Lower Abs' },
  { name: 'Kettlebell Swing', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Hamstrings' },
  { name: 'Barbell Front Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Deep Push-Up', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Dumbbell', description: 'Secondary: Inner Chest, Triceps Long Head' },
  { name: 'Dumbbell One-Arm Front Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: '' },
  { name: 'Barbell Reverse Curl', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Barbell', description: 'Secondary: Brachialis, Inner Biceps' },
  { name: 'Dumbbell Plie Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Quads, Glute Max' },
  { name: 'Dumbbell Farmers Carry', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Dumbbell', description: 'Secondary: Lower Back, Traps' },
  { name: 'Barbell Deep Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Stiff-Leg Deadlift', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Lower Back, Glute Max' },
  { name: 'Trap Bar Deadlift', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Quads, Hamstrings' },
  { name: 'Dumbbell Arnold Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder, Triceps Long Head' },
  { name: 'Weighted Side Bend', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Barbell', description: 'Secondary: Deep Core' },
  { name: 'Barbell Wrist Curl (Posterior)', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Barbell', description: 'Secondary: Inner Forearm' },
  { name: 'Barbell Bent-Over Row (Reverse Grip)', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Middle Back' },
  { name: 'Weight Plate Front Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Weight Plate', description: '' },
  { name: 'Bodyweight Sumo Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max, Inner Thigh' },
  { name: 'Barbell Bicep Curl (Wide Grip)', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Barbell', description: 'Secondary: Outer Biceps, Brachialis' },
  { name: 'Dumbbell Alternating Front Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: '' },
  { name: 'Dumbbell Reverse Bicep Curl', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Dumbbell', description: 'Secondary: Outer Forearm, Brachialis' },
  { name: 'Barbell Push Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Quads, Triceps Lateral Head' },
  { name: 'Barbell Sumo Deadlift', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Hamstrings, Quads' },
  { name: 'Dumbbell Single-Leg Cobra', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Wood Chop', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Dumbbell', description: 'Secondary: Deep Core' },
  { name: 'Dumbbell Rear Deltoid Row', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Middle Back' },
  { name: 'Dumbbell Hammer Curl to Press', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Dumbbell', description: 'Secondary: Front Shoulder, Outer Biceps' },
  { name: 'Weighted Trunk Rotation', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Barbell', description: 'Secondary: Deep Core' },
  { name: 'Barbell Front Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: '' },
  { name: 'Dumbbell 3 Way Shoulder Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder' },
  { name: 'Dumbbell Rotational Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Dumbbell', description: 'Secondary: Inner Biceps, Obliques' },
  { name: 'Dumbbell One-Arm Lateral Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: '' },
  { name: 'Barbell Calf Raise', category: 'RESISTANCE', muscleGroup: 'Lower Legs', equipment: 'Barbell', description: 'Secondary: Lower Calf' },
  { name: 'Barbell Overhead Triceps Extension', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Barbell', description: 'Secondary: Triceps Lateral Head, Triceps Medial Head' },
  { name: 'Kettlebell Farmer\'s Carry', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Kettlebell', description: '' },
  { name: 'Weight Plate Rotation', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Weight Plate', description: 'Secondary: Deep Core, Upper Abs' },
  { name: 'Dumbbell Alternating Deltoid Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Front Shoulder, Deep Core' },
  { name: 'EZ Bar Close Grip Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'EZ Curl Bar', description: 'Secondary: Inner Biceps, Brachialis' },
  { name: 'EZ Bar French Press', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'EZ Curl Bar', description: 'Secondary: Triceps Lateral Head, Triceps Medial Head' },
  { name: 'Dumbbell Hammer Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Triceps Lateral Head, Side Shoulder' },
  { name: 'Pendlay Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Middle Back' },
  { name: 'Barbell Rack Pull', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Dumbbell Bent-Over Row (Palms In)', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Dumbbell', description: 'Secondary: Middle Back, Rear Shoulder' },
  { name: 'Dumbbell Alternating Triceps Kickback', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Dumbbell', description: 'Secondary: Triceps Lateral Head, Triceps Medial Head' },
  { name: 'Kettlebell One-Arm Swing', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Hamstrings, Traps' },
  { name: 'Weight Plate Shrug', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Weight Plate', description: 'Secondary: Middle Back' },
  { name: 'Kettlebell Front Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Kettlebell', description: 'Secondary: Glute Max' },
  { name: 'Weight Plate Wall Sit', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Weight Plate', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Bicep Curl (Reverse Grip)', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Dumbbell', description: 'Secondary: Outer Biceps, Inner Biceps' },
  { name: 'Barbell Zercher Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max, Deep Core' },
  { name: 'Dumbbell One-Arm Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder' },
  { name: 'Dumbbell Shoulder Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder' },
  { name: 'Kettlebell Leg Pass', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Kettlebell', description: 'Secondary: Obliques, Lower Back' },
  { name: 'Dumbbell One-Arm Bicep Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Dumbbell', description: 'Secondary: Inner Biceps, Top of Forearm' },
  { name: 'Trap Bar Shrugs', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Middle Back' },
  { name: 'Kettlebell Suitcase Carry', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Kettlebell', description: 'Secondary: Obliques' },
  { name: 'Dumbbell Upright Row', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Traps' },
  { name: 'Barbell Behind the Back Shrug', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Middle Back' },
  { name: 'Barbell Ab Rollout', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Barbell', description: 'Secondary: Lower Abs' },
  { name: 'Barbell Curl (Close Grip)', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Barbell', description: 'Secondary: Inner Biceps, Brachialis' },
  { name: 'Dumbbell Cuban Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder' },
  { name: 'Kettlebell Sumo High Pull', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Hamstrings, Traps, Side Shoulder' },
  { name: 'Kettlebell Figure Eight', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Kettlebell', description: 'Secondary: Obliques, Lower Back' },
  { name: 'Barbell Romanian Deadlift From Deficit', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Hamstrings' },
  { name: 'Dumbbell Renegade Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Dumbbell', description: 'Secondary: Middle Back, Deep Core' },
  { name: 'Dumbbell Bent-Over Triceps Extension', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Dumbbell', description: 'Secondary: Triceps Medial Head, Lower Back' },
  { name: 'Kettlebell One-Arm Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Kettlebell', description: 'Secondary: Middle Back' },
  { name: 'Dumbbell Push Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Triceps Long Head' },
  { name: 'Kettlebell Thruster', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Kettlebell', description: 'Secondary: Front Shoulder, Glute Max' },
  { name: 'Barbell Bicep Drag Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Barbell', description: 'Secondary: Inner Biceps, Brachialis' },
  { name: 'Barbell Overhead Front Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: '' },
  { name: 'Kettlebell One-Arm Snatch', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Traps, Hamstrings' },
  { name: 'Barbell Rear Deltoid Row', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Middle Back, Traps' },
  { name: 'Trap Bar Romanian Deadlift', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max, Lower Back' },
  { name: 'Barbell Rear Military Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Side Shoulder' },
  { name: 'Barbell Lateral Lunge', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Kettlebell Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Kettlebell', description: 'Secondary: Middle Back' },
  { name: 'Barbell Clean and Jerk', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Kettlebell Alternating Floor Press', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Kettlebell', description: 'Secondary: Triceps Long Head' },
  { name: 'Kettlebell Pistol Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Kettlebell', description: 'Secondary: Glute Max' },
  { name: 'Kettlebell Windmill', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Kettlebell', description: 'Secondary: Deep Core, Lower Back' },
  { name: 'Dumbbell One-Arm Triceps Kickback', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Dumbbell', description: 'Secondary: Triceps Medial Head' },
  { name: 'Weight Plate Reverse Curl', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Weight Plate', description: 'Secondary: Outer Forearm, Brachialis' },
  { name: 'Dumbbell One-Arm Hammer Curl', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Dumbbell', description: 'Secondary: Outer Biceps, Inner Biceps' },
  { name: 'Barbell Squat (Wide Stance)', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max, Inner Thigh' },
  { name: 'Barbell Clean Deadlift', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Lower Back' },
  { name: 'Barbell Drag Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Barbell', description: 'Secondary: Inner Biceps, Brachialis' },
  { name: 'Trap Bar Overhead Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Side Shoulder, Triceps Long Head' },
  { name: 'Barbell Clean', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Traps, Hamstrings' },
  { name: 'Trap Bar Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Hack Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Squat to Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max, Front Shoulder' },
  { name: 'Barbell Push Press Behind the Neck', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Triceps Lateral Head, Traps' },
  { name: 'Kettlebell Push-Up', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Kettlebell', description: 'Secondary: Triceps Long Head' },
  { name: 'Dumbbell Rotational Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Dumbbell', description: 'Secondary: Middle Back, Obliques' },
  { name: 'Dumbbell Jump Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Hang Clean', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Rocking Standing Calf Raise', category: 'RESISTANCE', muscleGroup: 'Lower Legs', equipment: 'Barbell', description: 'Secondary: Lower Calf' },
  { name: 'Kettlebell One-Arm Push Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Quads, Triceps Lateral Head' },
  { name: 'Dumbbell High Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Dumbbell', description: 'Secondary: Outer Biceps' },
  { name: 'Weight Plate Hand Squeeze', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Weight Plate', description: 'Secondary: Inner Biceps, Outer Biceps' },
  { name: 'Push-up to Renegade Row', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Barbell', description: '' },
  { name: 'Dumbbell Alternating Arnold Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder, Triceps Long Head' },
  { name: 'Dumbbell Alternating Bent-Over Reverse Fly', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Middle Back, Traps' },
  { name: 'Weight Plate High Front Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Weight Plate', description: '' },
  { name: 'Dumbbell Wall Squat Hold', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Alternating Lateral Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Traps' },
  { name: 'EZ Bar Bent-Over Row (Reverse Grip)', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'EZ Curl Bar', description: 'Secondary: Middle Back' },
  { name: 'Dumbbell Alternating Reverse Curl', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Dumbbell', description: 'Secondary: Outer Biceps, Inner Biceps' },
  { name: 'Barbell One-Arm Floor Press', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Barbell', description: 'Secondary: Triceps Long Head' },
  { name: 'Dumbbell Alternating Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder' },
  { name: 'Kettlebell Clean', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Hamstrings, Traps' },
  { name: 'Weighted Side Rotation', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Barbell', description: 'Secondary: Deep Core' },
  { name: 'Barbell Side Split Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max, Inner Thigh, Outer Thigh' },
  { name: 'Kettlebell Alternating Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Kettlebell', description: 'Secondary: Middle Back' },
  { name: 'Barbell Rear Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Triceps Lateral Head, Traps' },
  { name: 'Trap Bar Farmer\'s Walk', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Barbell', description: 'Secondary: Traps, Inner Forearm, Lower Back' },
  { name: 'Kettlebell Military Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head, Side Shoulder' },
  { name: 'Kettlebell One-Arm Military Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head, Side Shoulder' },
  { name: 'Dumbbell Lateral Lunge With Bicep Curl', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Snatch Shrug', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Barbell Squat with Narrow Stance', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Kettlebell Alternating Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Side Shoulder, Triceps Long Head' },
  { name: 'Kettlebell Renegade Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Kettlebell', description: 'Secondary: Deep Core, Middle Back' },
  { name: 'Barbell One-Arm Row', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Middle Back' },
  { name: 'Kettlebell Dead Clean', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Traps, Hamstrings' },
  { name: 'Calf Raise On A Dumbbell', category: 'RESISTANCE', muscleGroup: 'Lower Legs', equipment: 'Dumbbell', description: 'Secondary: Lower Calf' },
  { name: 'Weight Plate Sissy Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Weight Plate', description: '' },
  { name: 'Dumbbell One-Arm Reverse Curl', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Dumbbell', description: 'Secondary: Outer Biceps' },
  { name: 'Dumbbell One-Arm Triceps Extension (Reverse Grip)', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Dumbbell', description: 'Secondary: Triceps Lateral Head, Triceps Long Head' },
  { name: 'Dumbbell Dublin Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder' },
  { name: 'Kettlebell One-Arm Floor Press', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Kettlebell', description: 'Secondary: Triceps Long Head' },
  { name: 'Dumbbell One-Arm Upright Row', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Traps' },
  { name: 'Barbell Snatch Deadlift', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Hamstrings, Lower Back' },
  { name: 'Weight Plate Pinch', category: 'RESISTANCE', muscleGroup: 'Forearms', equipment: 'Weight Plate', description: 'Secondary: Outer Forearm' },
  { name: 'Barbell Kneeling Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Alternating Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder, Triceps Long Head' },
  { name: 'Barbell Overhead Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Trap Bar Bent-over Rows', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Middle Back' },
  { name: 'Dumbbell See Saw Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Triceps Lateral Head, Side Shoulder' },
  { name: 'Kettlebell One-Arm Clean and Jerk', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Quads, Hamstrings' },
  { name: 'Barbell Bradford Rocky Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Side Shoulder' },
  { name: 'Dumbbell One-Arm Shoulder Press (Palms In)', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder, Triceps Long Head' },
  { name: 'Barbell 1/2 Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Kettlebell Turkish Get-Up Squat', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Glute Max, Quads' },
  { name: 'Dumbbell Wall Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Squat to Bicep Curl', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max, Inner Biceps' },
  { name: 'Diagonal Plate Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Weight Plate', description: 'Secondary: Upper Chest' },
  { name: 'Dumbbell Squat Curl to Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Rear Delts Row to Neck', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Middle Back, Lats' },
  { name: 'Barbell Snatch', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Quads, Traps' },
  { name: 'Dumbbell Iron Cross', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: '' },
  { name: 'Barbell Power Clean from Blocks', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Kettlebell Arnold Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Side Shoulder, Triceps Lateral Head' },
  { name: 'Kettlebell Double Windmill', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Kettlebell', description: 'Secondary: Deep Core, Lower Back' },
  { name: 'Kettlebell Push Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head, Quads' },
  { name: 'Trap Bar Jump Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Kettlebell Turkish Get-Up Lunge', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: '' },
  { name: 'Barbell Side Bend', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Barbell', description: '' },
  { name: 'Barbell Stiff-Leg Deadlift (Wide Stance)', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Lower Back, Glute Max' },
  { name: 'Barbell Squat to Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Front Shoulder, Glute Max' },
  { name: 'EZ Bar French Press (Reverse Grip)', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'EZ Curl Bar', description: 'Secondary: Triceps Lateral Head, Triceps Long Head' },
  { name: 'Barbell Clean Pull', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Weight Plate One-Arm Shrug', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Weight Plate', description: 'Secondary: Deep Core, Middle Back' },
  { name: 'Kettlebell Advanced Windmill', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Kettlebell', description: 'Secondary: Deep Core, Lower Back' },
  { name: 'Kettlebell Hang Clean', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Traps, Hamstrings' },
  { name: 'Dumbbell Floor Press', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Dumbbell', description: 'Secondary: Triceps Long Head' },
  { name: 'Dumbbell One-Arm Bent-Over Reverse Fly', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Middle Back' },
  { name: 'Kettlebell Seated Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head, Side Shoulder' },
  { name: 'Dumbbell Bicep Curl With Stork Stance', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Dumbbell', description: 'Secondary: Inner Biceps, Brachialis' },
  { name: 'Barbell Jefferson Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max, Inner Thigh' },
  { name: 'Dumbbell Forward Lunge With Bicep Curl', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Power Snatch', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Traps, Quads' },
  { name: 'Kettlebell One-Arm Para Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head, Side Shoulder' },
  { name: 'Barbell Speed Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Alternating Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Side Shoulder' },
  { name: 'Barbell One-Arm Bicep Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Barbell', description: 'Secondary: Inner Biceps, Brachialis, Top of Forearm' },
  { name: 'Dumbbell One-Arm Arnold Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder' },
  { name: 'Barbell Round the World Shoulder Stretch', category: 'COOL-DOWN', muscleGroup: 'Shoulders', equipment: 'Barbell', description: '' },
  { name: 'Dumbbell One-Arm Hammer Shoulder Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Dumbbell', description: 'Secondary: Side Shoulder, Triceps Long Head' },
  { name: 'Barbell One-Arm Side Deadlift', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Hamstrings, Lower Back' },
  { name: 'Barbell 1/4 Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Deadlift to Bicep Curl', category: 'RESISTANCE', muscleGroup: 'Biceps', equipment: 'Barbell', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Kettlebell Alternating Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head' },
  { name: 'Barbell High Front Raise', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Upper Chest' },
  { name: 'Barbell Jerk', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Triceps Lateral Head, Quads' },
  { name: 'Barbell Rack Delivery', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Quads' },
  { name: 'Barbell Squat to Upright Row', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Traps, Side Shoulder, Glute Max' },
  { name: 'Barbell Snatch Pull', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Traps, Hamstrings' },
  { name: 'Barbell Kneeling Jump Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Hang Snatch', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Quads, Traps' },
  { name: 'Barbell Hang Clean Below the Knees', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Quads, Hamstrings' },
  { name: 'Kettlebell Jerk', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head, Quads' },
  { name: 'Kettlebell One-Arm Overhead Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Kettlebell', description: 'Secondary: Glute Max, Front Shoulder' },
  { name: 'Kettlebell Bent Press', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Obliques, Deep Core' },
  { name: 'Kettlebell Open Palm Clean', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Traps, Hamstrings' },
  { name: 'Barbell Split Jerk', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Traps' },
  { name: 'Kettlebell One-Arm Jerk', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head, Quads' },
  { name: 'Barbell Power Jerk', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Barbell', description: 'Secondary: Triceps Long Head' },
  { name: 'Barbell Split Jump', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Snatch Balance', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Lunge with Bicep Curl (Bowling Motion)', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Dumbbell', description: 'Secondary: Glute Max' },
  { name: 'Dumbbell Tricep Kickback with Stork Stance (Bowling Motion)', category: 'RESISTANCE', muscleGroup: 'Triceps', equipment: 'Dumbbell', description: 'Secondary: Triceps Lateral Head, Triceps Medial Head' },
  { name: 'Barbell Jerk Dip Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Barbell Frankenstein Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Glute Max' },
  { name: 'Kettlebell One-Arm Palm Clean', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Traps, Hamstrings' },
  { name: 'Barbell Hang Snatch Below the Knees', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Traps, Quads' },
  { name: 'Barbell One-Arm Snatch', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Quads' },
  { name: 'Barbell High Snatch', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Traps, Quads' },
  { name: 'Kettlebell Alternating Hang Clean', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Kettlebell', description: 'Secondary: Quads' },
  { name: 'Kettlebell One-Arm Split Jerk', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Kettlebell', description: 'Secondary: Triceps Lateral Head, Quads' },
  { name: 'Barbell Power Snatch From Blocks', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Quads' },
  { name: 'Barbell Squat Jerk', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Barbell', description: 'Secondary: Front Shoulder' },
  { name: 'Barbell Clean From Blocks', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Barbell', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Barbell Split Clean', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Hamstrings' },
  { name: 'Barbell Snatch From Blocks', category: 'RESISTANCE', muscleGroup: 'Glutes', equipment: 'Barbell', description: 'Secondary: Traps, Quads' },
  { name: 'Medicine Ball Overhead Slam', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Medicine Ball', description: 'Secondary: Upper Abs, Lower Abs' },
  { name: 'Medicine Ball Rotation', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Medicine Ball', description: 'Secondary: Deep Core' },
  { name: 'Medicine Ball Overhead Throw', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Medicine Ball', description: 'Secondary: Triceps Long Head' },
  { name: 'Medicine Ball Catch and Throw', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Medicine Ball', description: 'Secondary: Front Shoulder, Upper Chest' },
  { name: 'Medicine Ball Two-Arm Overhead Throw', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Medicine Ball', description: 'Secondary: Deep Core, Upper Chest' },
  { name: 'Medicine Ball Chest Pass', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Medicine Ball', description: 'Secondary: Inner Chest' },
  { name: 'Medicine Ball Chest Push', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Medicine Ball', description: 'Secondary: Triceps Long Head' },
  { name: 'Medicine Ball Chest Push from Stance', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Medicine Ball', description: 'Secondary: Inner Chest' },
  { name: 'Medicine Ball One-Arm Overhead Throw', category: 'RESISTANCE', muscleGroup: 'Shoulders', equipment: 'Medicine Ball', description: 'Secondary: Triceps Long Head, Upper Chest' },
  { name: 'Medicine Ball Chest Push to Run', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Medicine Ball', description: 'Secondary: Triceps Long Head' },
  { name: 'Medicine Ball Chest Throw (Supine)', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Medicine Ball', description: 'Secondary: Triceps Long Head' },
  { name: 'Medicine Ball Chest Push Push from Stance', category: 'RESISTANCE', muscleGroup: 'Chest', equipment: 'Medicine Ball', description: 'Secondary: Inner Chest' },
  { name: 'Plank', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Obliques' },
  { name: 'Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Lower Abs, Deep Core' },
  { name: 'Leg Raise', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Hip Flexors' },
  { name: 'Bodyweight Squat', category: 'RESISTANCE', muscleGroup: 'Upper Legs', equipment: 'Body Weight', description: 'Secondary: Glute Max' },
  { name: 'Air Bike', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Upper Abs, Obliques, Deep Core, Hip Flexors' },
  { name: 'Side Plank', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Deep Core, Glute Med/Min' },
  { name: 'Reverse Crunch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Upper Abs, Deep Core' },
  { name: 'Sit-Up', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Lower Abs, Hip Flexors' },
  { name: 'Mountain Climber', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Obliques, Hip Flexors' },
  { name: 'Alternating Heel Touch', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Upper Abs, Deep Core' },
  { name: 'Dead Bug', category: 'RESISTANCE', muscleGroup: 'Abs', equipment: 'Body Weight', description: 'Secondary: Lower Abs' },
  { name: 'Bird Dog', category: 'RESISTANCE', muscleGroup: 'Back', equipment: 'Body Weight', description: 'Secondary: Deep Core, Glute Max' },
  { name: 'Walking', category: 'CARDIO', muscleGroup: 'Other', equipment: 'Body Weight', description: 'Secondary: Glute Max, Hamstrings' },
  { name: 'Running', category: 'CARDIO', muscleGroup: 'Other', equipment: 'Body Weight', description: 'Secondary: Glute Max, Hamstrings, Upper Calf' },
];

// نداء مرة واحدة من console المتصفح بعد تسجيل دخول المدرب
// بيتحقق أولاً من أسماء التمارين الموجودة بالفعل في المكتبة (Firestore) ويتخطاها لتجنب التكرار
export async function seedImportedExercises() {
  const librarySnap = await getDocs(collection(db, 'artifacts', APP_ID, 'public', 'data', 'library'));
  const existingNames = new Set(
    librarySnap.docs.map(d => (d.data().name || '').trim().toLowerCase())
  );

  const results = [];
  for (const ex of IMPORTED_EXERCISES) {
    const key = ex.name.trim().toLowerCase();
    if (existingNames.has(key)) {
      results.push({ name: ex.name, skipped: true, reason: 'already in library' });
      continue;
    }
    try {
      const ref = await addDoc(
        collection(db, 'artifacts', APP_ID, 'public', 'data', 'library'),
        {
          name: ex.name,
          category: ex.category,
          muscleGroup: ex.muscleGroup,
          equipment: ex.equipment,
          sets: ex.category === 'RESISTANCE' ? '3' : '',
          reps: ex.category === 'RESISTANCE' ? '10' : '',
          tempo: '',
          cardioMetric: ex.category === 'CARDIO' ? 'duration' : 'duration',
          targetDuration: ex.category === 'CARDIO' ? 20 : 0,
          targetDistance: 0,
          targetCalories: 0,
          intervals: [],
          gifUrl: '',
          videoUrl: '',
          description: ex.description,
          alternatives: [],
          createdAt: serverTimestamp(),
        }
      );
      existingNames.add(key);
      results.push({ name: ex.name, id: ref.id, ok: true });
    } catch (e) {
      results.push({ name: ex.name, error: e.message, ok: false });
    }
  }
  console.table(results);
  console.log(`Added: ${results.filter(r => r.ok).length} | Skipped (duplicate): ${results.filter(r => r.skipped).length} | Failed: ${results.filter(r => r.error).length}`);
  return results;
}
